# services/transform/dbt_project.yml
name: "content_trend_advisor"
version: "1.0.0"
config-version: 2

profile: "content_trend_advisor"

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]

vars:
  youtube_raw_table: "raw_content"
  reddit_raw_table: "raw_content"

models:
  content_trend_advisor:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

snapshots:
  content_trend_advisor:
    +target_schema: snapshots