# YouTube Category ID to Name Mapping
# Source: https://developers.google.com/youtube/v3/docs/videoCategories/list

categories:
  "1": "Film & Animation"
  "2": "Autos & Vehicles" 
  "10": "Music"
  "15": "Pets & Animals"
  "17": "Sports"
  "18": "Short Movies"
  "19": "Travel & Events"
  "20": "Gaming"
  "21": "Videoblogging"
  "22": "People & Blogs"
  "23": "Comedy"
  "24": "Entertainment"
  "25": "News & Politics"
  "26": "Howto & Style"
  "27": "Education"
  "28": "Science & Technology"
  "29": "Nonprofits & Activism"
  "30": "Movies"
  "31": "Anime/Animation"
  "32": "Action/Adventure"
  "33": "Classics"
  "34": "Documentary"
  "35": "Drama"
  "36": "Family"
  "37": "Foreign"
  "38": "Horror"
  "39": "Sci-Fi/Fantasy"
  "40": "Thriller"
  "41": "Shorts"
  "42": "Shows"
  "43": "Trailers"

# Categories relevant to tech/productivity niche
tech_categories:
  - "Science & Technology"
  - "Education" 
  - "Howto & Style"
  - "Gaming"  # Tech gaming content
  - "News & Politics"  # Tech news

# Categories to generally avoid for tech focus
avoid_categories:
  - "Music"
  - "Sports"
  - "Entertainment"
  - "Comedy"
  - "Film & Animation"
  - "Pets & Animals"
